language: csharp
mono: none
dotnet: 2.1.200
script:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./scripts/build.sh; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/deploy.sh; fi
before_deploy:
- python ./scripts/predeploy.py
deploy:
  provider: releases
  api_key:
    secure: PdDcyu9JGcYeWCCfpHxA597iSzQPSj/p6MK+bGsI0cpJW7Yrvp+BcIJ0hindfVNOXiodxcAKHwx/PJFE4G6YoPkJTVmVobUE1xhCci+20IyJqBGTT2u33icVTYJbI0sDLk9IIuUTyK1LyRszd0KMTQNB6W7cBIycXtdGH7Nvg09QnY3yo5dE2bLZZu8RvFkiA0nhzcSPEUth7fJc+2X/2V9Xgtkpaykrn77yMzGymUi8m9DThDuN1SKPGep1HULdolHWd2iDDGeDiYGy1IxwajynKPw3scGijf0jTuoGcQC3fpUXHsPaVaRdTa1esYitD+UGiQ51tXrwPJ6Jn4NxM8P248t7O7/+ie3kQtOP33ciBKclgqHKkzB+o6pMCoY4tgtOGRx1kd+bUmhepGn50aj9wAbfM1W+9p0hiDVYbHIouI0Kg6fCQv1BhgRdElz7hqtXY7x1AHz1BJRVNAiQwac7XM3BMx7vBJb2XyHMM26wET7OOfKTTRtmybT5r5ONpbpLe/BHeuM7M3RphUmV28p8JFvwzd80DMXl7pIhujarNsREm0MGc8KnhW6MZLkAJnZl9k3XMBvmzyLgXCJVutoDw0Bb5t4KCkvOKSS06amC4YQg02jzBwipUC1Cp310HcPDG93tzvkLR279Lz3y7wRly/gKhDyVJchk44/vIrg=  
  file: "$TRAVIS_BUILD_DIR/releases/Stardew.MPSaveEditor-$TRAVIS_BUILD_ID.zip"
  skip_cleanup: true
  on:
    all_branches: true

